### PR TITLE
Add word boundary kind type

### PR DESCRIPTION
**Pull request by natecook1000**
This updated the word boundary algorithm selection API to accept a named type rather than a Bool, as described in the Unicode for String Processing proposal

### CODE REVIEW

**Comment by natecook1000** [comment]
@swift-ci Please test

**Review by rxwei — APPROVED** [review]

**Comment by natecook1000** [comment]
@swift-ci Please test Linux platform

**Comment by natecook1000** [comment]
@swift-ci Please test Linux platform

**Comment by natecook1000** [comment]
Replaced by #295.

**Pull request closed without merging**
