### PR TITLE
Fix a few DSL APIs

### LINKED ISSUE #537: `CharacterClass.newlineSequence` crashes as unsupported
For the following:

```swift
import RegexBuilder

let r = Regex {
  CharacterClass.newlineSequence
}
_ = try! r.wholeMatch(in: "\n")
```

Crashes with:

```
Fatal error: 'try!' expression unexpectedly raised an error: Unsupported: 'Consumer for unconverted(_StringProcessing.DSLTree._AST.Atom(ast: \n))'
  /Users/hamish/src/swift-experimental-string-processing/Sources/_StringProcessing/ConsumerInterface.swift:317
```

rdar://96330096

### LINKED ISSUE #539: Implement `CharacterClass.anyNonNewline`
This is proposed in https://github.com/apple/swift-evolution/blob/main/proposals/0363-unicode-for-string-processing.md, but doesn't seem to be on main yet.

rdar://97029702

### LINKED ISSUE #553: `CharacterClass.any` doesn't match newlines
https://github.com/apple/swift-evolution/blob/main/proposals/0363-unicode-for-string-processing.md states that:

```swift
  /// This character class is equivalent to the regex syntax "dot"
  /// metacharacter in single-line mode: `(?s:.)`.
  public static var any: CharacterClass { get }
```

however the following:

```swift
Regex {
  CharacterClass.any
}
```

does not match against a newline input.

rdar://96509234

### LINKED ISSUE #571: DSL's `.startOfLine` should match at start of line.
Currently the DSL's `.startOfLine` anchor maps to the literal's `^`, which is start of input or line depending on options. As proposed it should match at the start of any line. We should probably rename the AST's anchor kind and DSLTree should support a lowered anchor.

rdar://97029630

### PR DESCRIPTION
**Pull request by hamishknight**
Fix `CharacterClass.newlineSequence` such that it doesn't crash, `CharacterClass.any` such that it matches newlines, and implement `CharacterClass.anyNonNewline`.

Also fix `Anchor.startOfLine` and `Anchor.endOfLine` such that they always match newlines.

Resolves #537 (rdar://96330096)
Resolves #553 (rdar://96509234)
Resolves #571 (rdar://97029630)
Resolves #539 (rdar://97029702)

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Review by milseman — APPROVED** [review]
LGTM

**Comment by hamishknight** [comment]
@swift-ci please test

**Pull request merged**
