### PR TITLE
[5.7] [DNM] Cherry-pick batch test PR

### PR DESCRIPTION
**Pull request by hamishknight**
Batch test PR against the Swift repo for:

- https://github.com/apple/swift-experimental-string-processing/pull/582
- https://github.com/apple/swift-experimental-string-processing/pull/569
- https://github.com/apple/swift-experimental-string-processing/pull/588
- https://github.com/apple/swift-experimental-string-processing/pull/583

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by stephentyrone** [comment]
Hamish, we can close this one out now, right?

**Comment by hamishknight** [comment]
Yeah

**Pull request closed without merging**
