### PR TITLE
[5.7] Remove (?X) and (?u) for now

### PR DESCRIPTION
**Pull request by Azoy**
This is a cherry pick of https://github.com/apple/swift-experimental-string-processing/pull/480

### CODE REVIEW

**Review by milseman — APPROVED** [review]

**Comment by Azoy** [comment]
@swift-ci please test

**Comment by Azoy** [comment]
@swift-ci please test Linux

**Comment by Azoy** [comment]
@swift-ci please test Linux

**Comment by Azoy** [comment]
@swift-ci please test

**Review by stephentyrone — APPROVED** [review]

**Pull request merged**
