### PR TITLE
Tweak libswiftLexRegexLiteral interface

### PR DESCRIPTION
**Pull request by hamishknight**
From the review feedback on https://github.com/apple/swift/pull/40595, update the interface here so it would have the ability to better recover from lexing errors in the future.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test Linux

**Comment by hamishknight** [comment]
@swift-ci please test Linux

**Comment by hamishknight** [comment]
@milseman I added a couple of extra platforms to the `#available`s to hopefully fix the build issue in https://ci.swift.org/job/swift-PR-macos/30333/

**Review by milseman — APPROVED** [review]
LGTM for now. We'll eventually want a model of a diagnostics engine for the future, because we want to be able to issue notes and fixits and warnings, but this is a good lexing interface. The latter can be added to the parsing interface.

**Comment by milseman** [comment]
@swift-ci please test linux platform

**Pull request merged**
