### PR TITLE
Regex Type and Overview V2 and accompanying tests/changes

### PR DESCRIPTION
**Pull request by milseman**
- Adds the motivation as test cases (CC @hamishknight @rxwei @natecook1000 @itingliu in case this is helpful).
- V2 of Regex Type and Overview, ready for proposal
- Minor adjustments to regex syntax pitch (still WIP)
- Adds `compiling` argument label, renames API to match pitch thread, etc

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test

**Review by rxwei — APPROVED** [review]

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please test

**Pull request merged**
