### PR TITLE
[5.7] Fix a few DSL APIs

### LINKED ISSUE #537: `CharacterClass.newlineSequence` crashes as unsupported
For the following:

```swift
import RegexBuilder

let r = Regex {
  CharacterClass.newlineSequence
}
_ = try! r.wholeMatch(in: "\n")
```

Crashes with:

```
Fatal error: 'try!' expression unexpectedly raised an error: Unsupported: 'Consumer for unconverted(_StringProcessing.DSLTree._AST.Atom(ast: \n))'
  /Users/hamish/src/swift-experimental-string-processing/Sources/_StringProcessing/ConsumerInterface.swift:317
```

rdar://96330096

### LINKED ISSUE #539: Implement `CharacterClass.anyNonNewline`
This is proposed in https://github.com/apple/swift-evolution/blob/main/proposals/0363-unicode-for-string-processing.md, but doesn't seem to be on main yet.

rdar://97029702

### LINKED ISSUE #553: `CharacterClass.any` doesn't match newlines
https://github.com/apple/swift-evolution/blob/main/proposals/0363-unicode-for-string-processing.md states that:

```swift
  /// This character class is equivalent to the regex syntax "dot"
  /// metacharacter in single-line mode: `(?s:.)`.
  public static var any: CharacterClass { get }
```

however the following:

```swift
Regex {
  CharacterClass.any
}
```

does not match against a newline input.

rdar://96509234

### LINKED ISSUE #571: DSL's `.startOfLine` should match at start of line.
Currently the DSL's `.startOfLine` anchor maps to the literal's `^`, which is start of input or line depending on options. As proposed it should match at the start of any line. We should probably rename the AST's anchor kind and DSLTree should support a lowered anchor.

rdar://97029630

### PR DESCRIPTION
**Pull request by hamishknight**
*5.7 cherry-pick of https://github.com/apple/swift-experimental-string-processing/pull/578 + https://github.com/apple/swift-experimental-string-processing/pull/580*

Fix `CharacterClass.newlineSequence` such that it doesn't crash, `CharacterClass.any` such that it matches newlines, and implement `CharacterClass.anyNonNewline`.

Also fix `Anchor.startOfLine` and `Anchor.endOfLine` such that they always match newlines.

Resolves #537 
Resolves #553
Resolves #571
Resolves #539

Resolves rdar://97029702

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Review by milseman — APPROVED** [review]
LGTM

**Comment by Azoy** [comment]
Explanation:
The proposed `CharacterClass.anyNonNewline` was not yet implemented, and a few character classes and anchors were not behaving correctly as proposed. Specifically, `Character.newlineSequence` was crashing, `Character.any` was not matching newlines, and `Anchor.startOfLine` and `Anchor.endOfLine` were not always matching newlines.

Scope:
Part of this PR is purely additive in terms of `.anyNonNewline`, so existing clients are unaffected. The bug fixes in this PR should be purely bug fixes, existing clients who were relying on the buggy behavior will have different runtime behavior, but will otherwise still compile.

Main Branch PR:
https://github.com/apple/swift-experimental-string-processing/pull/578 and https://github.com/apple/swift-experimental-string-processing/pull/580

Resolves:
rdar://97029702

Risk:
Low

Reviewed By:
@milseman

Testing:
Added a bunch of tests to ensure that we are now correctly matching the various buggy character classes/anchors and added tests to ensure that `.anyNonNewline` works as intended.

**Review by stephentyrone — APPROVED** [review]

**Comment by hamishknight** [comment]
@swift-ci please test

**Pull request merged**
