### PR TITLE
Add tweaks for Android

### PR DESCRIPTION
**Pull request by buttaface**
This pull gets this repo to build and pass all the tests natively on my Android AArch64 phone.

### CODE REVIEW

**Comment by buttaface** [comment]
@Azoy, would you review?

**Review by Azoy — APPROVED** [review]
Looks reasonable to me, thanks!

**Comment by Azoy** [comment]
@swift-ci please test

**Comment by buttaface** [comment]
MacOS CI is broken, other pulls fail with the same error.

**Comment by natecook1000** [comment]
Sorry about that! CI is fixed now.

@swift-ci Please test

**Comment by buttaface** [comment]
Can someone merge? Would be nice to have this in the 5.8 branch tomorrow.

**Pull request merged**
