### PR TITLE
Track source locations through the AST

### PR DESCRIPTION
**Pull request by milseman**
- Source range tracking for groups and quantification
- Overhaul AST to be enum of structs and use protocols for common operations

Still need to track way more source locations, but I think it's important to merge this soon so we can build on it.

### CODE REVIEW

**Comment by milseman** [comment]
Rebased and more fleshed out

**Comment by milseman** [comment]
@hamishknight can you take a look at this?

@rxwei I fixed the bug where non-capturing groups were saying they were capturing. It wasn't too bad, just had to update some of the legacy compilation test cases.

**Review by hamishknight — APPROVED** [review]
LGTM!

**Comment by milseman** [comment]
@swift-ci please test linux platform

**Pull request merged**
