### PR TITLE
Refactor generator script

### PR DESCRIPTION
**Pull request by milseman**

### CODE REVIEW

**Comment by milseman** [comment]
Refactors to have these helpers:

```
func captureTypeList(_ arity: Int) -> String {
  (0..<arity).map { "C\($0)" }.joined(separator: ", ")
}
func optionalCaptureTypeList(_ arity: Int) -> String {
  (0..<arity).map { "C\($0)?" }.joined(separator: ", ")
}
```

**Comment by milseman** [comment]
Now numbers captures consistently, i.e. `<W, C1, C2>` instead of `<W, C0, C1>`

**Comment by milseman** [comment]
Fixed indentation, the `disfavoredOverload` when empty  was over indenting the declarations

**Comment by milseman** [comment]
@swift-ci please test

**Review by natecook1000 — APPROVED** [review]
:100:

**Pull request merged**
