### PR TITLE
Revise doc comments for API reference style (Swift 5.7)

### PR DESCRIPTION
**Pull request by amartini51**
Cherry pick of https://github.com/apple/swift-experimental-string-processing/pull/350

### CODE REVIEW

**Comment by amartini51** [comment]
Confirmed that, after resolving merge conflicts, this cherry-pick PR makes the same changes as the original by running:

```
opendiff =(git diff 882c2be...ac618f6) =(git diff origin/swift/release/5.7...amartini/docs_91301229_5.7) 
```

**Comment by stephentyrone** [comment]
Alex, I attempted to clean up the conflicts here, but it probably needs another pass, because the signature of one of the operations changed.

**Comment by amartini51** [comment]
Thanks @stephentyrone, I'm taking a look through the merge conflicts.  Can you point me at the signature that changed?  I'll want to make sure the docs on 'main' get updated for that.

**Comment by amartini51** [comment]
Swift 5.7 has shipped — closing this cherry-pick.

**Pull request closed without merging**
