### PR TITLE
Overhaul quantification optimizations

### PR DESCRIPTION
**Pull request by Catfish-Man**
Finishing up @milseman's https://github.com/apple/swift-experimental-string-processing/pull/710

### CODE REVIEW

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Comment by Catfish-Man** [comment]
New assertion already paying off

Test Case 'AlgorithmTests.testMatchesCollection' started at 2024-02-03 00:43:54.316
_StringProcessing/MEQuantify.swift:133: Assertion failed

**Comment by Catfish-Man** [comment]
@swift-ci please test

**Comment by Catfish-Man** [comment]
Nate thinks the remaining test failure is due to CI trying to run the tests concurrently

**Comment by Catfish-Man** [comment]
Failure appears to be pre-existing, going ahead and merging

**Comment by milseman** [comment]
@Catfish-Man Err, this is hitting an assert introduced by this PR. Should we revert and fix?

**Comment by milseman** [comment]
Is it a problem for tests to run concurrently? Why?

**Comment by Catfish-Man** [comment]
Ok. I discussed with Nate first and made sure it passed locally

**Pull request merged**
