### PR TITLE
Make variadic builder overloads AEIC (take 2)

### PR DESCRIPTION
**Pull request by Azoy**
This marks all of the variadic builder overloads as @_alwaysEmitIntoClient so that these aren't permanently part of our ABI.

### CODE REVIEW

**Comment by Azoy** [comment]
@swift-ci please test

**Comment by Azoy** [comment]
@swift-ci please test

**Review by rxwei — APPROVED** [review]

**Review by milseman — APPROVED** [review]
This seems like a better route than first take.

If we instead had some of these in `_StringProcessing`, would we be able to outright remove `DSLTree` as SPI? That would be an even cleaner not-technically-stable ABI.

**Comment by rxwei** [comment]
> If we instead had some of these in _StringProcessing, would we be able to outright remove DSLTree as SPI? That would be an even cleaner not-technically-stable ABI.

That would require the `_RegexFactory` to be public, whereas it can be internal in the RegexBuilder module today. I don't think the SPI is concerning since the two modules are always co-evolved and built together.

**Comment by rxwei** [comment]
IMO it's better to have SPI than make things public. Today, I don't think _StringProcessing exports any `public` underscored symbols.

**Comment by milseman** [comment]
I don't think we're talking about the same thing. I'm not saying anything should be non-SPI public that isn't API. Why is it better to make DSLTree SPI-public instead of making _RegexFactory SPI-public?

**Comment by rxwei** [comment]
Oh sorry I misunderstood. My impression was one couldn't use SPIs in AEIC functions? I may be wrong.

**Comment by Azoy** [comment]
Ah that's right, if _RegexFactory was public SPI in string processing, we couldn't use it in AEIC.

**Comment by rxwei** [comment]
In that case, it is indeed a SPI/public tradeoff. IMO not exposing new public decls is better.

**Pull request closed without merging**
