### PR TITLE
Convert scalar escape sequences to DSL scalars

### PR DESCRIPTION
**Pull request by hamishknight**
Follow-up to https://github.com/apple/swift-experimental-string-processing/pull/226.

Convert AST escape sequences that represent a scalar value (e.g `\f`, `n`, `\a`) into scalars in the DSL tree. This allows the matching engine to match against them.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
GitHub acting weird, but I did request a review from both of you

**Review by natecook1000 — APPROVED** [review]
LGTM!

**Comment by hamishknight** [comment]
@swift-ci please test

**Pull request merged**
