### PR TITLE
🍒 Fix duplicate symbols static-linking failure by renaming symbols

### PR DESCRIPTION
**Pull request by etcwilde**
Cherry-picking https://github.com/apple/swift-experimental-string-processing/pull/544.
Should resolve: https://github.com/apple/swift/issues/62034

### CODE REVIEW

**Comment by etcwilde** [comment]
@swift-ci please smoke test

**Review by Azoy — APPROVED** [review]
Thank you!

**Review by ephemer — APPROVED** [review]
LGTM and it appears to be already in the main branch, so I'm hoping this can be merged soon to unblock static linking workflows in 5.7.x

**Review by tomerd — APPROVED** [review]

**Comment by tomerd** [comment]
cc @shahmishal

**Review by michaelknoch — APPROVED** [review]

**Pull request merged**
