### PR TITLE
[5.7] Character class and scalar coalescing fixes

### LINKED ISSUE #395: Case insensitivity behavior of character class ranges differs from PCRE
PCRE allows `(?i)[B-a]`, which matches e.g `B`, `[`, `b`, and `A`. However, we crash at runtime.

rdar://96898279

### LINKED ISSUE #401: Digit matching behaving as intended?
Reposted from the Swift forums: https://forums.swift.org/t/bad-digit-matching-bugreport-regarding-se-0354-regex-literals/57262/1

Problem: Some digit character groups match number-like grapheme clusters.

```
// this matches:
try /[1-2]/.wholeMatch(in: "1️⃣")

// still matches:
try /[1-2]/.asciiOnlyDigits().wholeMatch(in: "1️⃣")

// does not match:
try /[12]/.wholeMatch(in: "1️⃣")
```

Above described behavior seems inconsistent and difficult to predict. Shouldn't [1-2] and [12] be identical? Should they match anything outside of ascii?

Note: :one: is U+0031 (ascii digit 1) U+FE0F (VARIATION SELECTOR-16) U+20E3 (COMBINING ENCLOSING KEYCAP)

Same is true for 1︎⃣: U+0031 (ascii digit 1) U+FE0E (VARIATION SELECTOR-15) U+20E3 (COMBINING ENCLOSING KEYCAP)

rdar://96898279

### LINKED ISSUE #572: Adjacent scalars in the DSL should be coalesced
For example:

```swift
    let r3 = Regex {
      "👨" as UnicodeScalar
      "\u{200D}" as UnicodeScalar
      "👨" as UnicodeScalar
      "\u{200D}" as UnicodeScalar
      "👧" as UnicodeScalar
      "\u{200D}" as UnicodeScalar
      "👦" as UnicodeScalar
    }
```

should match `"👨‍👨‍👧‍👦"`.

### LINKED ISSUE #573: Better preserve scalar syntax in DSL transform
We currently transform `a\u{301}` into:

```swift
Regex {
  "á"
}
```

we ought to try and preserve the `\u{301}` syntax the user wrote.

### LINKED ISSUE #586: Quoted character class sequences don't match in scalar mode
For `[\Qe\u{301}\E]` (where `e\u{301}` is a literal decomposed character) in scalar semantic mode, it still matches as if it were in grapheme mode, i.e matching `e\u{301}`, but not `e`.

rdar://97209131

### PR DESCRIPTION
**Pull request by hamishknight**
*5.7 cherry-pick of #570 + #574 + #559*

- Fixes character class range matching
  - Resolves #401 
  - Resolves #395
- Fixes scalar coalescing
  - Resolves #572 
  - Resolves #573
- Fixes scalar semantic matching of quoted sequences in character classes
  - Resolves #586 

Resolves rdar://97386173

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Review by stephentyrone — APPROVED** [review]

**Comment by hamishknight** [comment]
- Explanation: Fixes the matching behavior of custom character classes. This includes properly coalescing adjacent scalars to produce correct grapheme semantics, fixing ranges to exhibit more consistent matching behavior, and fixing the scalar semantic behavior of quoted sequences. The scalar coalescing fixes also apply to the DSL, such that adjacent scalars in a DSL concatenation are coalesced to produce correct grapheme matching semantics.

- Scope: Affects runtime matching semantics of custom character classes in regex literals, as well as adjacent unicode scalars values in the DSL.

- Radar: rdar://97386173

- Risk: Low/Medium – This change reworks a decent amount of matching engine logic around character classes, however many test cases have been added to ensure correctness. Most of the other changes are generalizations of existing logic.

- Testing: Added test cases to the repo to ensure the matching behavior is correct.

- Reviewer: @stephentyrone

**Comment by hamishknight** [comment]
@swift-ci please test

**Comment by hamishknight** [comment]
@swift-ci please test

**Pull request merged**
