### PR TITLE
Revise doc comments for API reference style (Swift 5.7-04182022)

### PR DESCRIPTION
**Pull request by amartini51**
Cherry pick of #350

### CODE REVIEW

**Comment by amartini51** [comment]
@milseman Thanks for reviewing the main PR.  I've confirmed locally that this PR has the same set of changes.  Is there anything else I should do before merging this one?

```
opendiff \
=(git diff origin/main...amartini/docs_91301229) \
=(git diff origin/swift/release/5.7-04182022...amartini/docs_91301229_5.7-04182022)
```

**Comment by milseman** [comment]
We need high-level sign off on this if it's even possible to land at this point

**Comment by stephentyrone** [comment]
Do we have this on 5.7 as well?

**Comment by milseman** [comment]
I don't think so, no

**Comment by stephentyrone** [comment]
Let's please get a clone for 5.7 up so that this at least gets into a later beta.

**Comment by amartini51** [comment]
Re-cherry-picked for the Swift 5.7 branch in #378.  Looks like it's too late in the release process to do anything with this PR, so closing it.

**Pull request closed without merging**
