### PR TITLE
[5.7] Integrate API changes into release/5.7

### PR DESCRIPTION
**Pull request by Azoy**

### CODE REVIEW

**Comment by Azoy** [comment]
@swift-ci please test

**Review by natecook1000 — APPROVED** [review]

**Comment by rxwei** [comment]
Triggered compiler tests here: https://github.com/apple/swift/pull/42446

**Comment by Azoy** [comment]
@swift-ci please test

**Comment by Azoy** [comment]
@swift-ci please test

**Comment by milseman** [comment]
@swift-ci please test macOS platform

**Review by stephentyrone — APPROVED** [review]

**Pull request merged**
