### PR TITLE
[5.7] Improve Unicode/UTS18 and semantic level support (#268)

### PR DESCRIPTION
**Pull request by hamishknight**
*5.7 cherry-pick of https://github.com/apple/swift-experimental-string-processing/pull/268*

* Add tests for UTS18 level support (incomplete)
* Implement canonical equivalence tests
* Fix canonical equivalence at different levels
* Test named chars x semantic level
* Enable loose matching on \N{...} scalar names
* Make Unicode property classes work with semantics

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

**Review by natecook1000 — APPROVED** [review]
:shipit:

**Comment by milseman** [comment]
Do you have a swift-ci run for this?

**Comment by hamishknight** [comment]
Ack no, let's take this in https://github.com/apple/swift-experimental-string-processing/pull/409 if we can

**Pull request closed without merging**
