### PR TITLE
Throwing customization hooks

### PR DESCRIPTION
**Pull request by milseman**
Adds test to try out throwing custom code. Adds processor support.

### CODE REVIEW

**Comment by milseman** [comment]
@swift-ci please test

**Comment by milseman** [comment]
I would like to add the following, but we don't take `throws` on `Capture` currently (should we?)

```

    struct Poison: Error, Hashable {}
    struct Overflow: Error, Hashable {}

    let addressRegex = Regex {
      "0x"
      Capture(OneOrMore(.hexDigit)) { hex -> Int in
        guard let i = Int(hex, radix: 16) else {
          throw Overflow()
        }
        if i == 0xdeadbeef {
          throw Poison()
        }
        return i
      }
    }
```

**Review by rxwei — APPROVED** [review]

**Comment by rxwei** [comment]
> we don't take `throws` on `Capture` currently (should we?)

I don't know. Perhaps we should raise it on the forum?

**Comment by milseman** [comment]
Added support for `throws` everywhere

**Comment by milseman** [comment]
@rxwei it seems you beat me to the second commit by 4 minutes, drat. Care to take a look at the rest?

**Comment by rxwei** [comment]
What's the proposed new behavior? Is it the following:
- Throwing means abort in both `Capture` and `TryCapture`.
- `TryCapture` backtracks when the capture transform returns nil.

**Comment by milseman** [comment]
Yes, that’s right

**Comment by rxwei** [comment]
LGTM

**Comment by rxwei** [comment]
The non-Optional-returning ones on TryCapture could probably be removed.

**Comment by milseman** [comment]
Done.

@swift-ci please test

**Pull request merged**
