### PR TITLE
[Integration] main (06f40f6) -> swift/main

### PR DESCRIPTION
**Pull request by rintaro**
This should not require swift changes. But [89b80bf](https://github.com/apple/swift-experimental-string-processing/pull/328/commits/89b80bfe180ea3940ae9a35bb5765f69f448ec4e) in this PR is required by https://github.com/apple/swift/pull/42583

### CODE REVIEW

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rintaro** [comment]
@swift-ci Please test

**Comment by rxwei** [comment]
@swift-ci please test

**Review by rxwei — APPROVED** [review]

**Comment by rintaro** [comment]
Integration tests passed in:
https://ci.swift.org/job/swift-PR-macos/1395/
https://ci.swift.org/job/swift-PR-Linux/1433/
https://ci-external.swift.org/job/swift-PR-windows/1044/

**Pull request merged**
