### PR TITLE
[Integration] main (39c54d3) -> swift/main

### PR DESCRIPTION
**Pull request by rxwei**
This integration includes main up to commit 39c54d3, which includes Slava's workaround for rdar://89791117.

### CODE REVIEW

**Comment by rxwei** [comment]
@swift-ci please test

**Comment by rxwei** [comment]
Note: Do not merge until the compiler has been tested against this.

**Comment by slavapestov** [comment]
I'm testing this PR with the compiler in https://github.com/apple/swift/pull/41663.

**Comment by rxwei** [comment]
Ready to merge together with #41663 whenever both pass tests.

**Pull request merged**
