### PR TITLE
De-genericize processor, engine, etc.

### PR DESCRIPTION
**Pull request by milseman**
Provides only modest performance improvements (it was already getting specialized), but makes it possible to add String-specific specializations.

### CODE REVIEW

**Comment by milseman** [comment]
Based on top of https://github.com/apple/swift-experimental-string-processing/pull/501

**Comment by milseman** [comment]
@swift-ci please test

**Comment by rctcwyvrn** [comment]
The comparer in https://github.com/apple/swift-experimental-string-processing/pull/505 seems to show more than just modest improvements!

```
=== Improvements ====================================================
- emailLookaheadNoMatchesFirst		88.4ms	92.1ms	-3.72ms	-4.0%
- emailRFCNoMatchesAll			109ms	115ms	-6.05ms	-5.0%
- emailLookaheadNoMatchesAll		88.4ms	92ms	-3.66ms	-4.0%
- ReluctantQuantWhole			14.2ms	17ms	-2.78ms	-16.0%
- emailRFCAll				54.6ms	116ms	-61.7ms	-53.0%
- notFoundFirst				15.3ms	17.6ms	-2.28ms	-13.0%
- EagarQuantWithTerminalWhole		6.63ms	7.94ms	-1.31ms	-16.0%
- emailLookaheadAll			103ms	215ms	-112ms	-52.0%
- htmlAll				14ms	37.6ms	-23.6ms	-63.0%
- cssAll				5.36ms	15ms	-9.63ms	-64.0%
- HangulSyllableAll			8.55ms	15ms	-6.4ms	-43.0%
- GraphemeBreakNoCapAll			10.1ms	22.2ms	-12.1ms	-55.0%
- emailRFCNoMatchesFirst		109ms	115ms	-6.05ms	-5.0%
- notFoundAll				15.3ms	17.6ms	-2.32ms	-13.0%
```

**Review by natecook1000 — APPROVED** [review]
LGTM!

**Pull request merged**
